* What We’re Building
Today, we’re going to build an interactive tic-tac-toe game.

If you like, you can check out the final result here: Final Result. Don’t worry if the code doesn’t make sense to you yet, or if it uses an unfamiliar syntax. We will be learning how to build this game step by step throughout this tutorial.

[[https://codepen.io/gaearon/pen/gWWZgR?editors=0010][Try playing the game.]] You can also click on a button in the move list to go “back in time” and see what the board looked like just after that move was made.

Once you get a little familiar with the game, feel free to close that tab, as we’ll start from a simpler template in the next sections.

* Install
  Make sure you have node and npm

install create-react-app 
#+begin_src  bash
  $ npm install -g create-react-app
  $ create-react-app tic-tac-toe
#+end_src

remove the directory
#+begin_src bash
  $ cd tic-tac-toe
  $ rm -f src/*
#+end_src

Add a file named index.css in the src/ folder with this CSS code.

Add a file named index.js in the src/ folder with this JS code.

Add these three lines to the top of index.js in the src/ folder:
#+begin_src javascript
  import React from 'react';
  import ReactDOM from 'react-dom';
  import './index.css';
#+end_src

Now if you run npm start in the project folder and open [[http://localhost:3000][http://localhost:3000]] in the browser, you should see an empty tic-tac-toe field.

